# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MBRShapefileGenerator
                                 A QGIS plugin
 This plugin is used to generate shapefiles of map based routing zones stored on the areapoint table
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-07
        copyright            : (C) 2025 by Dan Cahoon
        email                : dcahoon@korterra.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MBRShapefileGenerator class from file MBRShapefileGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mbr_shapefile_generator import MBRShapefileGenerator
    return MBRShapefileGenerator(iface)
